sudo: required
language: cpp
os:
  - linux
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - freeglut3-dev
      - libvulkan-dev
      - libdmx-dev
      - cmake
      - xorg-dev
compiler:
  - g++-8
script: 
  - mkdir cmakebuild
  - cd cmakebuild
  - cmake ..
  - cmake --build .
