sudo: required
language: cpp
os:
  - linux
dist: bionic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - freeglut3-dev
      - libvulkan-dev
      - libdmx-dev
      - cmake
      - xorg-dev
compiler:
  - g++-8
script:
  - mkdir cmakebuild
  - cd cmakebuild
  - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 ..
  - cmake --build . --target BrotBoxEngineGTest
  - cmake --build . --target Example3D
  - cmake --build . --target ExampleMandelbrot
  - cmake --build . --target ExampleMandelbrotShader
  - cmake --build . --target ExampleParticleGravity
  - cmake --build . --target ExampleSnake
  - cmake --build . --target ExampleCurves
