sudo: required
language: cpp
os:
  - linux
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - freeglut3-dev
      - libvulkan-dev
      - libdmx-dev
      - cmake
      - xorg-dev
compiler:
  - g++-8
script: 
  - git clone https://github.com/glfw/glfw
  - cd glfw
  - sudo cmake .
  - sudo make
  - sudo make install
  - cd ..
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - make dirs
  - make all
